### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-timestamp-transform#1]
Moving from astronomerio/integration-issues#25

**Comment by benjamingregory** [comment]
@byerc I think you've got enough on your plate beyond this. Is this at a place that you can pass it off easily or is it better waiting until you have more availability?

**Comment by byerc** [comment]
There hasn't really been much work done on it. I don't mind finishing it, if it's urgent you can pass it on. What's written now is not what Mike and Greg had been working on. I was still in the process of digesting their pseudocode before getting pulled off and put onto empower. If you assign it to someone else, I can send them the pseudocode and have them give it a go. Either way works for me.

**Comment by benjamingregory** [comment]
Ok - I've moved it to Backlog and we'll just give it back to you when there's time. There no clear urgency right now.

**Comment by benjamingregory** [comment]
@byerc - I'm assigning this to Austin since you have enough else on your plate. Can you send over the pseudocode for him to get started?

**Comment by byerc** [comment]
@austin-toot Hello, what's currently in index.js has been refactored by Greg and Mike. 
`transform(config) {
       return function mapper(obj) {
           const fields = Object.keys(config.fields); //createdAt, showings.start
           for (let field of fields) {
               const transforms = fields[field];
               transformField(field, transforms, obj);
           }
           return obj;

           const fnMapper = _.map(config.fields, (transformDefs, key) => { // [], createdAt
               return transformDefs.map(transformDef => {
                   if (transformDef.type === 'timezone') {
                       //pass first parameter to return transformTimezone pass parameters for transformTimezone
                       return curry(this.transformTimeZone)(transformDef.from, transformDef.to)
                   }
               });
           });

           const result = _.map(obj, (val, key) => {
               const fns = fnMapper[key];
               const currentVal = _.get(key);
               const result = fns.reduce((acc, fn) => {
                   return fn(acc);
               }, currentValue);
               return _.set(obj, key, result);
           })
           return result;
     }`

This is extremely rough pseudocode of how they wanted it done. I stress extremely rough. I'd say if you have any questions to go to Mike as I was still in the process of digesting it myself before getting pulled off of this. Hopefully this is enough for you to get started. If you have any general questions, slack me at any time.

**Comment by benjamingregory** [comment]
@austin-toot @noahbass Has this been passed off? What is the status?
